### ISSUE TITLE
pagination bootstrap wont work

### ISSUE THREAD

**Issue by delacruzjames** [rweng/jquery-datatables-rails#170]
# not working
$(document).ready ->
  $('.offers-table table').dataTable({
     sPaginationType: "bootstrap",
  });

# working but no bootstrap style
$(document).ready ->
  $('.offers-table table').dataTable({
     pagingType: "full_numbers",
  });

how can i implement bootstrap pagination thanks

**Comment by jh125486** [comment]
You just have to link in the DataTable Bootstrap JS/CSS and use 'full_numbers' for pagingType.

[Bootstrap 3 config](https://github.com/rweng/jquery-datatables-rails#twitter-bootstrap-3-installation)

Make sure you only load the `jquery.dataTables.bootstrap` file
```

**Comment by ricardodovalle** [comment]
Hi @delacruzjames,  this thread can be closed?

**Comment by delacruzjames** [comment]
@ricardodovalle yah got it thanks

**Comment by ricardodovalle** [comment]
Thansk @jh125486 :clap: :+1:  and @delacruzjames

**Comment by Evan-M** [comment]
Hey, sorry to re-open this... I can file a separate issue, but this seemed pertinent. 

Some Background:
I just updated the gem from `3.1.1` to `3.3.0`.  Everything was working before, but I was doing a bunch of housekeeping, and updating outdated gems. 

I am using Bootstrap 2 styles, and have implemented them as documented in the [README - Bootstrap 2 Installation](https://github.com/rweng/jquery-datatables-rails#twitter-bootstrap-2-installation).  As specified, I have set the `pagingType: "bootstrap"` when I initialize the datatables plugin.

As of the update, setting the `pagingType` to `"bootstrap"` throws an exception, and no datatable is rendered.  If I set the `pagingType` to `"full_numbers"` or `"simple_numbers"`, the plugin works but the pagination links are unstyled.

After setting some breakpoints in the browser, I can see that where the exception is raised (inside the `_fnFeatureHtmlPaginate` method), that the `DataTable.ext.pager` dictionary has no key `bootstrap`. So the fact the the exception is raise I guess makes sense. 

Is there still supposed to be a `pagingType: "bootstrap"` for bootstrap 2 styles? or should I be using `"full_numbers"` like for bootstrap 3?  (and yes, I'm aware that bootstrap 2 is no longer developed and that I should update to bootstrap 3, but my hands are tied on that one at the moment).

On a side note, perhaps wrapping this bit in a try/catch structure in the `_fnFeatureHtmlPaginate` method  would prevent the javascript from completely failing... but that belongs in the datatables javascript implementation, rather than in this gem.
