### ISSUE TITLE
Sortable icon miss

### ISSUE THREAD

**Issue by neokain** [rweng/jquery-datatables-rails#183]
![screen shot 2015-07-14 at 21 55 16](https://cloud.githubusercontent.com/assets/11659/8676385/6106614e-2a73-11e5-8c9f-f5be8c1c27dd.png)

I install normally follow README.

**Comment by asithade** [comment]
+1

**Comment by donschmitz** [comment]
I don't understand why you would need to install ghe glyphicons gem when they are part of bootstrap.
I'm upgrading from 3.2.0 and all looks and works fine but with 3.3.0 the icons for sort direction are arrow heads rather than the triangles from 3.2.0.  I don't mind the arrow heads but the down arrow when selected looks like a wifi icon.
