### ISSUE TITLE
couldn't find file 'dataTables/jquery.dataTables.bootstrap3'

### ISSUE THREAD

**Issue by nekapoor** [rweng/jquery-datatables-rails#94]
Hello, 

I followed your instructions and in my app, I get this error.  I'm not sure if anyone else has experienced this, but I have no idea how to solve it. 

Any ideas would be greatly appreciated. Thanks so much.

**Comment by heber28** [comment]
i get the same error, but i changed the asset files in this way:

# app/assets/javascripts/application.js
//= require dataTables/jquery.dataTables
//= require dataTables/bootstrap/2/jquery.dataTables.bootstrap

# app/assets/stylesheets/application.css
*= require dataTables/bootstrap/2/jquery.dataTables.bootstrap

because i was using bootstrap 2
https://github.com/rweng/jquery-datatables-rails

this worked fine

**Comment by stevenm** [comment]
I had a much simpler reason, the installer had inserted the require line in my application js

//= require dataTables/bootstrap/3/jquery.dataTables.bootstrap

BEFORE the Bootstrap require line 

swapping them around so require bootstrap first then data tables solved
